
ISSUE_STATUS_REGISTERING = 'registering'
ISSUE_STATUS_COMMON_DOCUMENTS_REQUEST = 'common_documents_request'
ISSUE_STATUS_SURVEY = 'survey'
ISSUE_STATUS_SCORING = 'scoring'
ISSUE_STATUS_ADDITIONAL_DOCUMENTS_REQUEST = 'additional_documents_request'
ISSUE_STATUS_PAYMENTS = 'payments'
ISSUE_STATUS_FINAL_DOCUMENTS_APPROVAL = 'final_documents_approval'
ISSUE_STATUS_FINISHED = 'finished'
ISSUE_STATUS_CANCELLED = 'cancelled'

TENDER_EXEC_LAW_44_FZ = '44-fz'
TENDER_EXEC_LAW_223_FZ = '223-fz'

TENDER_CONTRACT_TYPE_SUPPLY_CONTRACT = 'supply'
TENDER_CONTRACT_TYPE_SERVICE_CONTRACT = 'service'
TENDER_CONTRACT_TYPE_WORKS_CONTRACT = 'works'

BG_TYPE_APPLICATION_ENSURE = 'application_ensure'
BG_TYPE_CONTRACT_EXECUTION = 'contract_execution'

CURRENCY_RUR = 'rur'
CURRENCY_USD = 'usd'
CURRENCY_EUR = 'eur'

IFOPC_INITIATOR_FINANCE_ORG = 'finance_org'
IFOPC_INITIATOR_ISSUER = 'issuer'
