
ISSUE_STATUS_REGISTERING = 'registering'
ISSUE_STATUS_REVIEW = 'review'
ISSUE_STATUS_FINISHED = 'finished'
ISSUE_STATUS_CANCELLED = 'cancelled'

TENDER_EXEC_LAW_44_FZ = '44-fz'
TENDER_EXEC_LAW_223_FZ = '223-fz'
TENDER_EXEC_LAW_185_FZ = '185-fz'
TENDER_EXEC_LAW_COMMERCIAL = 'commercial'
TENDER_EXEC_LAW_CUSTOMS = 'customs'
TENDER_EXEC_LAW_VAT = 'vat'

TENDER_CONTRACT_TYPE_SUPPLY_CONTRACT = 'supply'
TENDER_CONTRACT_TYPE_SERVICE_CONTRACT = 'service'
TENDER_CONTRACT_TYPE_WORKS_CONTRACT = 'works'

BG_TYPE_APPLICATION_ENSURE = 'application_ensure'
BG_TYPE_CONTRACT_EXECUTION = 'contract_execution'

CURRENCY_RUR = 'rur'
CURRENCY_USD = 'usd'
CURRENCY_EUR = 'eur'

IFOPC_INITIATOR_FINANCE_ORG = 'finance_org'
IFOPC_INITIATOR_ISSUER = 'issuer'

ISSUE_CREDIT_REPAYMENT_SCHEDULE_EQUAL_SHARES = 'equal_shares'
ISSUE_CREDIT_REPAYMENT_SCHEDULE_END_OF_TERM = 'end_of_term'

CREDIT_PLEDGE_TYPE_DEPOSIT = 'deposit'
CREDIT_PLEDGE_TYPE_REAL_ESTATE = 'real_estate'
CREDIT_PLEDGE_TYPE_OTHER = 'other'

FO_PRODUCT_CONDITIONS_INSURANCE_TYPE_REAL_ESTATE = 'real_estate'
FO_PRODUCT_CONDITIONS_INSURANCE_TYPE_PLEDGE = 'pledge'

FO_PRODUCT_PROPOSE_DOC_HEAD_PASSPORT = 'head_passport'
FO_PRODUCT_PROPOSE_DOC_HEAD_STATUTE = 'statute'

CREDIT_PURPOSE_TYPE_CONTRACT_EXEC = 'contract_exec'
CREDIT_PURPOSE_TYPE_WORK_CAPITAL_REFILL = 'work_capital_refill'
