
- hosts: all
  tasks:
    - name: Update APT cache
      apt: update_cache=yes
      become: true

    - name: Install software
      apt: name={{ item }} state=present
      with_items:
        - python
        - python3
        - python-pip
        - git
        - virtualenv
        - nodejs-legacy
        - npm
        - nginx
        - uwsgi
        - uwsgi-plugin-python3
        - gettext
      become: true

    - name: Install bower to manage static files packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - bower
        - grunt

    - name: Prepare project directory tree
      file: state=directory path=/srv/marer/
      become: true

    - name: Clone repository
      git:
        dest=/srv/marer/
        force=no
        repo=git@bitbucket.org:vladi-z/marer.git
        accept_hostkey=true
        version={{git_branch}}
      become: true

    - name: Install requirements
      pip:
        requirements: /srv/marer/requirements.txt
        virtualenv: /srv/virtualenv/
        virtualenv_python: python3.5

    - name: Configure Web Server - part 1
      copy:
        src=nginx.conf
        dest=/etc/nginx/sites-available/marer.ru.conf

    - name: Configure Web Server - part 2
      file:
        src=/etc/nginx/sites-available/marer.ru.conf
        dest=/etc/nginx/sites-enabled/marer.ru
        state=link

    - name: Setup SSL Certificates
      copy:
        src={{ item }}
        dest=/srv/{{ item }}
      with_items:
        - marer.ru.crt
        - marer.ru.key

    - name: Reload nginx
      service: name=nginx state=reloaded

    - name: Configure Web Server - part 3
      copy:
        src=uwsgi.ini
        dest=/etc/uwsgi/apps-available/marer.ru.ini

    - name: Configure Web Server - part 4
      file:
        src=/etc/uwsgi/apps-available/marer.ru.ini
        dest=/etc/uwsgi/apps-enabled/marer.ru.ini
        state=link

    - name: Reload uWSGI
      service: name=uwsgi state=reloaded

    - name: Primary build static files - npm requirements install
      command: npm install chdir=/srv/marer/marer/static/{{ item }}
      with_items:
        - bootstrap
        - frontend
      become: true

    - name: Primary build static files - grunt dist build
      command: grunt dist chdir=/srv/marer/marer/static/{{ item }}
      with_items:
        - bootstrap
      become: true

    - name: Build frontend static part with npm
      command: npm run build chdir=/srv/marer/marer/static/{{ item }}
      with_items:
        - frontend
      become: true

    - name: Cleaning installation mostly after static files patches
      command: git reset --hard chdir=/srv/marer/
      become: true
