# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=32)),
                ('kpp', models.CharField(max_length=32)),
                ('ogrn', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
