# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0002_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
