# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 12:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import marer.models.base
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0007_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marer.models.base.documents_upload_path)),
            ],
        ),
    ]
