# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 12:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0008_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_issue_links', to='marer.Document')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_documents', to='marer.Issue')),
            ],
        ),
    ]
