# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 12:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0009_issuedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_links', to='marer.Document')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_documents', to='marer.Issuer')),
            ],
        ),
    ]
