# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0010_issuerdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='static page name')),
                ('_seo_h1', models.CharField(blank=True, default='', max_length=512, verbose_name='name on page')),
                ('_seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='browser title')),
                ('_seo_description', models.CharField(blank=True, default='', max_length=512, verbose_name='page desctiption')),
                ('_seo_keywords', models.CharField(blank=True, default='', max_length=512, verbose_name='page keywords')),
                ('page_content', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='page content')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'static page',
                'verbose_name_plural': 'static pages',
            },
        ),
    ]
