# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0011_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOrgProductConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_product', models.CharField(choices=[('BankGuaranteeProduct', 'Банковская гарантия'), ('CreditProduct', 'Кредит'), ('LeasingProduct', 'Лизинг')], max_length=32)),
                ('finance_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_conditions', to='marer.FinanceOrganization')),
                ('bg_44_app_ensure_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_44_app_ensure_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_44_app_ensure_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_44_contract_exec_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_44_contract_exec_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_44_contract_exec_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_223_app_ensure_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_223_app_ensure_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_223_app_ensure_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_223_contract_exec_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_223_contract_exec_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_223_contract_exec_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_185_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_185_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_185_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_ct_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_ct_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_ct_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_vat_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_vat_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_vat_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_customs_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_customs_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bg_customs_interest_rate', models.FloatField(blank=True, null=True)),
                ('personal_presence_required', models.BooleanField(default=False)),
                ('bg_review_term_days', models.PositiveIntegerField(default=1)),
                ('bg_insurance_type', models.CharField(blank=True, choices=[('pledge', 'Недвижимое имущество'), ('pledge', 'Залог')], max_length=32, null=True)),
                ('bg_insurance_value', models.PositiveSmallIntegerField(default=0)),
                ('bg_bank_account_opening_required', models.BooleanField(default=False)),
                ('credit_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_interest_rate', models.FloatField(blank=True, null=True)),
                ('leasing_min_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('leasing_max_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('leasing_interest_rate', models.FloatField(blank=True, null=True)),
                ('bg_regions_blacklist', models.ManyToManyField(blank=True, to='marer.Region')),
                ('bg_sectors_blacklist', models.ManyToManyField(blank=True, to='marer.OKVED2')),
            ],
        ),
    ]
