# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0012_financeorgproductconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFinanceOrgPropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marer.FinanceOrganization')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marer.Issue')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issuefinanceorgpropose',
            unique_together=set([('issue', 'finance_org')]),
        ),
    ]
