# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 08:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import marer.models.base
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0013_issuefinanceorgpropose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeproductpage',
            name='product_icon',
            field=models.ImageField(blank=True, null=True, upload_to=marer.models.base.finance_products_page_images_upload_path),
        ),
    ]
