# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0014_set_financeproductpage_product_icon_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='sum',
            new_name='bg_sum',
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_currency',
            field=models.CharField(choices=[('rur', 'Рубль'), ('usd', 'Доллар'), ('eur', 'Евро')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_type',
            field=models.CharField(choices=[('application_ensure', 'Обеспечение заявки'), ('contract_execution', 'Исполнение контракта')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_fact_address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_foreign_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_education_level',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_first_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_industry_work_experience',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_last_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_middle_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_org_position_and_permissions',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_org_work_experience',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_passport_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_passport_issued_by',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_passport_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_passport_series',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_phone',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_residence_address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_head_share_in_authorized_capital',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_ifns_reg_cert_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_ifns_reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_legal_address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_okopf',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_okpo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_okved',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_prev_org_info',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_registration_date',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_contract_type',
            field=models.CharField(choices=[('supply', 'Поставка товара'), ('service', 'Оказание услуг'), ('works', 'Выполнение работ')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_exec_law',
            field=models.CharField(choices=[('44-fz', '44-ФЗ'), ('223-fz', '223-ФЗ')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_gos_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_has_prepayment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_placement_type',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_responsible_full_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_responsible_inn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_responsible_kpp',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_responsible_legal_address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_responsible_ogrn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_start_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
