# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0016_issuefinanceorgproposeclarification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFinanceOrgProposeClarificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_messages', to='marer.IssueFinanceOrgProposeClarification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
