# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0020_issuebgprodfounderlegal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBGProdFounderPhysical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=512)),
                ('add_date', models.CharField(default='', max_length=512)),
                ('additional_business', models.CharField(default='', max_length=512)),
                ('country', models.CharField(default='', max_length=512)),
                ('auth_capital_percentage', models.CharField(default='', max_length=512)),
                ('address', models.CharField(default='', max_length=512)),
                ('passport_data', models.CharField(default='', max_length=512)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_founders_physical', to='marer.Issue')),
            ],
        ),
    ]
