# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0022_issuefinanceorgproposeformalizedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFinanceOrgProposeFinalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propose_final_links', to='marer.Document')),
                ('propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_documents', to='marer.IssueFinanceOrgPropose')),
            ],
        ),
    ]
