# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0025_issuefinanceorgpropose_final_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuefinanceorgpropose',
            name='final_decision',
            field=models.NullBooleanField(),
        ),
    ]
