# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 09:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0027_okved2_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='marer.Region'),
        ),
    ]
