# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0032_financeorganization_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='bg_currency',
            field=models.CharField(blank=True, choices=[('rur', 'Рубль'), ('usd', 'Доллар'), ('eur', 'Евро')], max_length=32, null=True, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bg_deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='крайний срок выдачи банковской гарантии'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bg_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения действия банковской гарантии'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bg_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала действия банковской гарантии'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bg_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bg_type',
            field=models.CharField(blank=True, choices=[('application_ensure', 'Обеспечение заявки'), ('contract_execution', 'Исполнение контракта')], max_length=32, null=True, verbose_name='тип банковской гарантии'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий к заявке'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_fact_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='фактический адрес заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_foreign_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='наименование заявителя на иностранном'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_full_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='полное наименование заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_education_level',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='образование руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_first_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='имя руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_industry_work_experience',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='опыт работы руководителя в отрасли'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_last_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='фамилия руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_middle_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='отчество руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_org_position_and_permissions',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='должность, полномочия руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_org_work_experience',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='стаж работы руководителя в компании'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи паспорта руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_passport_issued_by',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='кем выдан паспорт руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_passport_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='номер паспорта руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_passport_series',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='серия паспорта руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_phone',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='телефон руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_residence_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='адрес прописки руководителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_head_share_in_authorized_capital',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='доля руководителя в уставном капиталле'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_ifns_reg_cert_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='номер свидетельства о постановке на учет ИФНС'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_ifns_reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата постановки на учет в ИФНС'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_inn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_kpp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='КПП заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_legal_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='юридическй адрес заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_ogrn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ОГРН заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_okopf',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='код ОКОПФ (правовая форма) заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_okpo',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='код ОКПО заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_okved',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='код ОКВЭД (основное направление деятельности) заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_prev_org_info',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='предыдущее место работы руководителя, отрасль, должность'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_registration_date',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer_short_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='краткое наименование заявителя'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='private_comment',
            field=models.TextField(blank=True, default='', verbose_name='приватный комментарий к заявке'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.CharField(choices=[('BankGuaranteeProduct', 'Банковская гарантия'), ('CreditProduct', 'Кредит'), ('LeasingProduct', 'Лизинг')], max_length=32, verbose_name='банковский продукт'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('registering', 'Оформление заявки'), ('review', 'Рассмотрение заявки'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], max_length=32, verbose_name='статус заявки'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_contract_type',
            field=models.CharField(blank=True, choices=[('supply', 'Поставка товара'), ('service', 'Оказание услуг'), ('works', 'Выполнение работ')], max_length=32, null=True, verbose_name='вид работ в тендере'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_exec_law',
            field=models.CharField(blank=True, choices=[('44-fz', '44-ФЗ'), ('223-fz', '223-ФЗ')], max_length=32, null=True, verbose_name='закон исполнения тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_gos_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='госномер тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_has_prepayment',
            field=models.NullBooleanField(verbose_name='авансирование в тендере'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_placement_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='способ определения поставщика в тендере'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_responsible_full_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='полное наименование организатора тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_responsible_inn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН организатора тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_responsible_kpp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='КПП организатора тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_responsible_legal_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='юридический адрес организатора тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_responsible_ogrn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ОГРН организатора тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tender_start_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='начальная цена тендера'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
