# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0034_issuefinanceorgpropose_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuefinanceorgpropose',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания'),
        ),
    ]
