# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0041_financeproductpage_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='credit_product_cl_tranche_term',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='срок транша (в случае кредитной линии)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_product_interest_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='ставка (в % годовых)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_product_is_credit',
            field=models.NullBooleanField(verbose_name='кредит'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_product_is_credit_line',
            field=models.NullBooleanField(verbose_name='кредитная линия'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_product_is_overdraft',
            field=models.NullBooleanField(verbose_name='овердрафт'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_product_term',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='срок продукта'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_purpose',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='цель кредита (подробно)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_repayment_schedule',
            field=models.CharField(blank=True, choices=[('equal_shares', 'Равными долями'), ('end_of_term', 'В конце срока')], max_length=32, null=True, verbose_name='график погашения'),
        ),
        migrations.AddField(
            model_name='issue',
            name='credit_repayment_sources',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='источники погашения'),
        ),
    ]
