# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import marer.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0043_issuecreditpledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcasePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=marer.models.base.showcase_partners_logos_upload_path, verbose_name='logo')),
                ('name', models.CharField(max_length=512, verbose_name='partner name')),
                ('category', models.CharField(choices=[('banks', 'Банки'), ('insurance', 'Страховые'), ('leasing_factoring', 'Лизинговые и факторинговые'), ('gos_pub_foundations', 'Госструктуры, общественные организации и фонды')], max_length=32, verbose_name='partner category')),
            ],
            options={
                'verbose_name_plural': 'partners logos',
                'verbose_name': 'partners logo',
            },
        ),
    ]
