# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0044_showcasepartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeproductpage',
            name='template',
            field=models.CharField(blank=True, choices=[('marer/product_custom_bg.html', 'Специальный шаблон для банковских гарантий')], max_length=512, null=True, verbose_name='finance product page template'),
        ),
    ]
