# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0045_financeproductpage_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_managed_users', 'Can add managed users'), ('can_change_users_base_info', 'Can change users base info'), ('can_change_managed_users', 'Can change managed users'), ('can_add_managed_users_issues', 'Can add managed users issues'), ('can_change_managed_users_issues', 'Can change managed users issues'), ('can_add_managed_users_issues_proposes', 'Can add managed users issues proposes'), ('can_view_managed_users_issues_proposes', 'Can view managed users issues proposes'), ('can_add_managed_users_issues_proposes_clarifications', 'Can add managed users issues proposes clarifications'), ('can_add_managed_users_issues_proposes_clarifications_messages', 'Can add managed users issues proposes clarifications messages')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
