# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0046_update_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFinanceOrgProposeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propose_links', to='marer.Document')),
                ('propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propose_documents', to='marer.IssueFinanceOrgPropose', verbose_name='предложение заявки в банк')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propose_samples_links', to='marer.Document')),
            ],
            options={
                'verbose_name': 'документ для банка',
                'verbose_name_plural': 'документы для банка',
            },
        ),
    ]
