# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0047_issuefinanceorgproposedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOrgProductProposeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_product', models.CharField(choices=[('BankGuaranteeProduct', 'Банковская гарантия'), ('CreditProduct', 'Кредит'), ('LeasingProduct', 'Лизинг')], max_length=32)),
                ('name', models.CharField(default='', max_length=512)),
                ('code', models.CharField(blank=True, max_length=512, null=True)),
                ('finance_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_docs_samples', to='marer.FinanceOrganization')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fo_product_propose_samples_links', to='marer.Document')),
            ],
            options={
                'verbose_name': 'документ для банка',
                'verbose_name_plural': 'документы для банка',
            },
        ),
    ]
