# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0049_rebuild_credit_finance_org_product_conditions_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bg_commercial_contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения договора'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_commercial_contract_place_of_work',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='место выполнения работ'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_commercial_contract_sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата заключения договора'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_commercial_contract_subject',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='предмет договора'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_commercial_contract_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма контракта'),
        ),
    ]
