# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0050_add_issue_model_bg_commercial_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
    ]
