# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0051_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_broker',
            field=models.BooleanField(default=False, help_text='Определяет, рассчитывается ли для пользователя комиссия и видит ли он свои выплаты, как брокер', verbose_name='Статус брокера'),
        ),
    ]
