# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0053_add_issue_factoring_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='leasing_advance_payment_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Авансовый платеж (%)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_asset_operation_territory',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Территория эксплуатации предмета лизинга'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_bank_account_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Рассчетный счет заявителя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_bank_identification_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_bank_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_corr_account_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_holder_on_balance_inn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН балансодержателя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_holder_on_balance_kpp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='КПП балансодержателя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_holder_on_balance_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Балансодержатель'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_holder_on_balance_ogrn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ОГРН балансодержателя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_insurer_inn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН страхователя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_insurer_kpp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='КПП страхователя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_insurer_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Страхователь'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_insurer_ogrn',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ОГРН страхователя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_payment_schedule',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='График платежей'),
        ),
        migrations.AddField(
            model_name='issue',
            name='leasing_term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок лизинга (мес.)'),
        ),
    ]
