# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0056_issueleasingprodasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLeasingProdSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='', max_length=512, verbose_name='наименование поставщика/продавца')),
                ('supplier_head_fio', models.CharField(default='', max_length=512, verbose_name='ФИО руководителя')),
                ('supplier_contact_fio', models.CharField(default='', max_length=512, verbose_name='ФИО контактного лица поставщика/продавца')),
                ('supplier_contacts', models.CharField(default='', max_length=512, verbose_name='контакты')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasing_suppliers', to='marer.Issue')),
            ],
            options={
                'verbose_name': 'поставщик/продавец предмета лизинга',
                'verbose_name_plural': 'поставщики/продавцы предмета лизинга',
            },
        ),
    ]
