# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0057_issueleasingprodsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLeasingProdPayRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='', max_length=512, verbose_name='наименование, тип, модель')),
                ('payment_name', models.CharField(default='', max_length=512, verbose_name='наименование платежа')),
                ('payment_size', models.CharField(default='', max_length=512, verbose_name='сумма платежа')),
                ('payment_rule', models.CharField(default='', max_length=512, verbose_name='порядок и срок оплаты')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasing_pay_rules', to='marer.Issue')),
            ],
            options={
                'verbose_name': 'порядок и сроки оплаты',
                'verbose_name_plural': 'условия и сроки оплаты',
            },
        ),
    ]
