# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0058_issueleasingprodpayrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='credit_purpose_type',
            field=models.CharField(blank=True, choices=[('work_capital_refill', 'Пополнение оборотных средств'), ('contract_exec', 'Исполнение контракта')], max_length=32, null=True, verbose_name='цель кредита'),
        ),
    ]
