# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0059_issue_credit_purpose_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFactoringBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_inn', models.CharField(default='', max_length=512, verbose_name='наименование, ИНН')),
                ('avg_monthly_shipments', models.CharField(default='', max_length=512, verbose_name='средние отгрузки за последние 12 месяцев (млн руб. без НДС)')),
                ('operating_pay_deferment_days', models.IntegerField(blank=True, null=True, verbose_name='действующая отсрочка платежа, дней')),
                ('start_work_date', models.CharField(default='', max_length=512, verbose_name='дата начала работы')),
                ('required_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='требуемый кредитный лимит (млн руб. без НДС)')),
                ('debitor_share', models.CharField(default='', max_length=512, verbose_name='доля дебитора')),
                ('average_delay_days', models.IntegerField(blank=True, null=True, verbose_name='средние просрочки за 12 месяцев, дней')),
                ('sales_volume', models.CharField(default='', max_length=512, verbose_name='объем продаж за последние 12 месяцев (млн руб. без НДС)')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoring_buyers', to='marer.Issue')),
            ],
            options={
                'verbose_name_plural': 'покупатели на факторинговое обслуживание',
                'verbose_name': 'покупатель на факторинговое обслуживание',
            },
        ),
    ]
