# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0061_add_issue_factoring_sales_analyze_related_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tender_gos_number',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='госномер или ссылка на тендер'),
        ),
    ]
