# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0063_add_can_change_managed_fo_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cert_hash',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='cert_sign',
            field=models.TextField(blank=True, default=''),
        ),
    ]
