# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0064_add_user_model_signing_related_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueClarification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(choices=[('finance_org', 'Финансовая организация'), ('issuer', 'Заявитель')], max_length=32, verbose_name='инициатор')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name_plural': 'дозапросы',
                'verbose_name': 'дозапрос',
            },
        ),
        migrations.CreateModel(
            name='IssueClarificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_messages', to='marer.IssueClarification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'сообщения по дозапросу',
                'verbose_name': 'сообщение по дозапросу',
            },
        ),
        migrations.CreateModel(
            name='IssueProposeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('code', models.CharField(blank=True, choices=[('head_passport', 'Паспорт генерального директора (руководителя)'), ('statute', 'Устав организации')], max_length=512, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propose_links', to='marer.Document')),
            ],
            options={
                'verbose_name_plural': 'документы для банка',
                'verbose_name': 'документ для банка',
            },
        ),
        migrations.CreateModel(
            name='IssueProposeFinalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='название документа')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_final_links', to='marer.Document')),
            ],
            options={
                'verbose_name_plural': 'итоговые документы',
                'verbose_name': 'итоговый документ',
            },
        ),
        migrations.CreateModel(
            name='IssueProposeFormalizeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='название документа')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_formalize_links', to='marer.Document')),
            ],
            options={
                'verbose_name_plural': 'документы для оформления',
                'verbose_name': 'документ для оформления',
            },
        ),
        migrations.AlterUniqueTogether(
            name='issuefinanceorgpropose',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgpropose',
            name='finance_org',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgpropose',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposeclarification',
            name='propose',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposeclarificationmessage',
            name='clarification',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposeclarificationmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposedocument',
            name='propose',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposedocument',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposefinaldocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposefinaldocument',
            name='propose',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposeformalizedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='issuefinanceorgproposeformalizedocument',
            name='propose',
        ),
        migrations.RemoveField(
            model_name='financeorgproductproposedocument',
            name='finance_org',
        ),
        migrations.AddField(
            model_name='issue',
            name='final_decision',
            field=models.NullBooleanField(verbose_name='удовлетворена ли заявка'),
        ),
        migrations.AddField(
            model_name='issue',
            name='final_note',
            field=models.TextField(blank=True, default='', verbose_name='подпись к итоговым документам'),
        ),
        migrations.AddField(
            model_name='issue',
            name='formalize_note',
            field=models.TextField(blank=True, default='', verbose_name='подпись к документам для оформления'),
        ),
        migrations.AlterField(
            model_name='issuefinanceorgproposeclarificationmessagedocument',
            name='clarification_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_links', to='marer.IssueClarificationMessage'),
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgPropose',
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgProposeClarification',
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgProposeClarificationMessage',
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgProposeDocument',
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgProposeFinalDocument',
        ),
        migrations.DeleteModel(
            name='IssueFinanceOrgProposeFormalizeDocument',
        ),
        migrations.AddField(
            model_name='issueproposeformalizedocument',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalize_documents', to='marer.Issue'),
        ),
        migrations.AddField(
            model_name='issueproposefinaldocument',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_documents', to='marer.Issue'),
        ),
        migrations.AddField(
            model_name='issueproposedocument',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propose_documents', to='marer.Issue', verbose_name='предложение заявки в банк'),
        ),
        migrations.AddField(
            model_name='issueproposedocument',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propose_samples_links', to='marer.Document'),
        ),
        migrations.AddField(
            model_name='issueclarification',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='marer.Issue', verbose_name='заявка'),
        ),
    ]
