# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0068_rebuild_issue_balance_related_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='final_decision',
        ),
    ]
