# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import marer.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0069_remove_issue_final_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to=marer.models.base.documents_upload_path),
        ),
    ]
