# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0072_extend_document_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='application_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_docs_links', to='marer.Document'),
        ),
    ]
