# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0073_issue_application_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='avg_employees_cnt_for_prev_year',
            field=models.IntegerField(default=1, verbose_name='Средняя численность работников за предшествующий календарный год'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_is_benefeciary_form',
            field=models.NullBooleanField(verbose_name='БГ по форме Бенефециара'),
        ),
        migrations.AddField(
            model_name='issue',
            name='deal_has_beneficiary',
            field=models.CharField(blank=True, choices=[(False, 'Отсутствует'), (True, 'Присутствует')], max_length=32, null=True, verbose_name='бенефециар'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_indisputable_charge_off',
            field=models.NullBooleanField(verbose_name='право на бесспорное списание'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_accountant_org_or_person',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='ФИО гл.бухгалтера / наименование организации, осуществляющей ведение бух.учёта'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_activity_objective',
            field=models.CharField(blank=True, choices=[('profit_making', 'Получение прибыли'), ('other', 'Иное')], max_length=32, null=True, verbose_name='цели финансово-хозяйственной детяельности'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_bank_relations_term',
            field=models.CharField(blank=True, choices=[('short_term', 'Краткосрочные'), ('long_term', 'Долгосрочные')], max_length=32, null=True, verbose_name='срок отношений с Банком'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_business_reputation',
            field=models.CharField(blank=True, choices=[('positive', 'Положительная'), ('not_present', 'Отсутствует')], max_length=32, null=True, verbose_name='деловая репутация'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_finance_situation',
            field=models.CharField(blank=True, choices=[('satisfied', 'Удовлетворительное'), ('unsatisfied', 'Неудовлетворительное')], max_length=32, null=True, verbose_name='финансовое положение'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_funds_source',
            field=models.CharField(blank=True, choices=[('loan_funds', 'Заемные средства'), ('other', 'Иное')], max_length=32, null=True, verbose_name='источник происхождения денежных средств'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_has_overdue_debts_for_last_180_days',
            field=models.NullBooleanField(verbose_name='Наличие просроченной задолженности по всем кредитам за последние 180 дней'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_okato',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='код ОКАТО заявителя'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_collegial_executive_fio',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Коллегиальный исполнительный орган: ФИО'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_collegial_executive_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Коллегиальный исполнительный орган: наименование'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_directors_or_supervisory_board_fio',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Совет директоров (наблюдательный совет): ФИО'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_directors_or_supervisory_board_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Совет директоров (наблюдательный совет): наименование'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_other_fio',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Иной орган управления организации заявителя: ФИО'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_org_management_other_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Иной орган управления организации заявителя: наименование'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_overdue_debts_info',
            field=models.TextField(blank=True, default='', verbose_name='Причины и обстоятельства просрочек'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_post_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='почтовый адрес заявителя (с индексом) в т.ч. для отправки банковской гарантии'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_web_site',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Web-сайт'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tender_contract_subject',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='предмет контракта'),
        ),
    ]
