# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0075_alter_issue_deal_has_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOrgBeneficiaryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=512, verbose_name='ФИО')),
                ('legal_address', models.CharField(default='', max_length=512, verbose_name='адрес регистрации')),
                ('fact_address', models.CharField(default='', max_length=512, verbose_name='адрес фактического пребывания')),
                ('post_address', models.CharField(default='', max_length=512, verbose_name='почтовый адрес')),
                ('inn_or_snils', models.CharField(default='', max_length=512, verbose_name='ИНН/СНИЛС (при наличии)')),
                ('on_belong_to_pub_persons_info', models.CharField(default='', max_length=512, verbose_name='сведения о принадлежности к публичным лицам')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_beneficiary_owners', to='marer.Issue')),
            ],
            options={
                'verbose_name_plural': 'сведения о бенефициарных владельцах',
                'verbose_name': 'сведения о бенефициарном владельце',
            },
        ),
    ]
