# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0076_issueorgbeneficiaryowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOrgBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='наименование')),
                ('bik', models.CharField(default='', max_length=512, verbose_name='БИК')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_bank_accounts', to='marer.Issue')),
            ],
            options={
                'verbose_name': 'банковский счет принципала',
                'verbose_name_plural': 'банковские счета принципала',
            },
        ),
    ]
