# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0079_issue_sec_dep_conclusion_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMinimalCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма продукта от')),
                ('sum_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма продукта по')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='минимальная комиссия')),
                ('term_months_min', models.IntegerField(verbose_name='срок действия продукта от, мес.')),
                ('term_months_max', models.IntegerField(verbose_name='срок действия продукта по, мес.')),
            ],
        ),
    ]
