# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0080_bankminimalcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_issues', to=settings.AUTH_USER_MODEL, verbose_name='менеджер по заявке'),
        ),
    ]
