# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0081_issue_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproposedocument',
            name='is_approved_by_manager',
            field=models.NullBooleanField(verbose_name='подтверждено менеджером'),
        ),
    ]
