# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0084_delete_issueclarificationmessage_issuefinanceorgproposeclarificationmessagedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueClarificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_messages', to='marer.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'сообщения по заявке',
                'verbose_name': 'сообщение по заявке',
            },
        ),
        migrations.CreateModel(
            name='IssueFinanceOrgProposeClarificationMessageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('clarification_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_links', to='marer.IssueClarificationMessage')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_messages_links', to='marer.Document')),
            ],
        ),
    ]
