# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0085_issueclarificationmessage_issuefinanceorgproposeclarificationmessagedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOrgManagementCollegial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=512, verbose_name='наименование')),
                ('fio', models.CharField(default='', max_length=512, verbose_name='фио')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_management_collegial', to='marer.Issue')),
            ],
            options={
                'verbose_name_plural': 'коллегиальные исполнительные органы',
                'verbose_name': 'коллегиальный исполнительный орган',
            },
        ),
        migrations.CreateModel(
            name='IssueOrgManagementDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=512, verbose_name='наименование')),
                ('fio', models.CharField(default='', max_length=512, verbose_name='фио')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_management_directors', to='marer.Issue')),
            ],
            options={
                'verbose_name_plural': 'совет директоров',
                'verbose_name': 'совет директоров',
            },
        ),
        migrations.CreateModel(
            name='IssueOrgManagementOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=512, verbose_name='наименование')),
                ('fio', models.CharField(default='', max_length=512, verbose_name='фио')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_management_others', to='marer.Issue')),
            ],
            options={
                'verbose_name_plural': 'иные органы управления',
                'verbose_name': 'иной орган управления',
            },
        ),
    ]
