# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0087_issuemessagesproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tax_system',
            field=models.CharField(blank=True, choices=[('tax_usn', 'УСН'), ('tax_osn', 'ОСН'), ('tax_envd', 'ЕНВД'), ('tax_eshd', 'ЕСХД')], max_length=32, null=True, verbose_name='Система налогообложения'),
        ),
    ]
