# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0089_add_type_field_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='обязательный документ'),
        ),
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='max_bg_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='максимальная сумма'),
        ),
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='min_bg_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='минимальная сумма'),
        ),
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='tax_system',
            field=models.CharField(blank=True, choices=[('tax_usn', 'УСН'), ('tax_osn', 'ОСН'), ('tax_envd', 'ЕНВД'), ('tax_eshd', 'ЕСХД')], max_length=32, null=True, verbose_name='система налогообложения'),
        ),
        migrations.AddField(
            model_name='issueproposedocument',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='обязательный документ'),
        ),
    ]
