# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0089_add_type_field_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='additional_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_doc', to='marer.Document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_contract_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_contract_doc', to='marer.Document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='transfer_acceptance_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_acceptance_acts_links', to='marer.Document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='bg_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='bg_doc', to='marer.Document'),
        ),
    ]
