# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0091_new_docs_in_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Форма собственности')),
                ('okopf_codes', models.CharField(max_length=256, verbose_name='Коды ОКОПФ')),
            ],
            options={
                'verbose_name': 'форма собственности',
                'verbose_name_plural': 'формы собственности',
            },
        ),
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='form_ownership',
            field=models.ManyToManyField(blank=True, null=True, to='marer.FormOwnership', verbose_name='Форма собственности'),
        ),
    ]
