# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0092_add_form_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeorgproductproposedocument',
            name='if_not_finished_contracts',
            field=models.BooleanField(default=False, verbose_name='Запрашивать, если нет опыта завершенных контрактов'),
        ),
    ]
