# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0093_extend_finance_org_product_propose_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='contract_of_guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_of_guaranties', to='marer.Document', verbose_name='Согласие на взаимодействие с БКИ (поручителя)'),
        ),
    ]
