# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0093_extend_finance_org_product_propose_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='balance_code_2110_offset_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='выручка за предыдущий год'),
        ),
    ]
