# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0094_issue_balance_code_2110_offset_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tender_final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='конечная цена тендера'),
        ),
    ]
