# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0096_issue_issuer_oktmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_absent_info_about_court_acts_for_more_than_20_pct_of_net_assets',
            field=models.NullBooleanField(verbose_name='Отсутствие информации об исполнительных производствах Приницпала его Участников на сумму более 20% чистых активов Клиента'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_absent_info_about_legal_proceedings_as_defendant_for_more_than_30_pct_of_net_assets',
            field=models.NullBooleanField(verbose_name='Отсутствие информации о судебных разбирательствах Клиента в качестве ответчика (за исключением закрытых) на сумму более 30% чистых активов Клиента'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_contract_has_prepayment',
            field=models.NullBooleanField(verbose_name='Контракт предусматривает выплату аванса'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_contract_price_reduction_lower_than_50_pct_on_supply_contract',
            field=models.NullBooleanField(verbose_name='Снижение цены Контракта менее 50% если предмет контракта «Поставка»'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_all_bank_liabilities_less_than_max',
            field=models.NullBooleanField(verbose_name='Лимит на Принципала (группу взаимосвязанных Заемщиков) ВСЕХ обязательств Банка менее 18 000 000 руб'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_executed_contracts_on_44_or_223_or_185_fz',
            field=models.NullBooleanField(verbose_name='Клиент исполнил не менее 1 контракта в рамках законов № 94-ФЗ, 44-ФЗ, 223-ФЗ, 185-ФЗ (615 ПП)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_executed_contracts_with_comparable_advances',
            field=models.NullBooleanField(verbose_name='Клиент исполнял контракты с авансами сопоставимого или большего размера (допустимое отклонение в меньшую сторону не более 50 % включительно)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_executed_goverment_contract_for_last_3_years',
            field=models.NullBooleanField(verbose_name='Наличие исполненного государственного контракта за последние 3 года'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_executed_gte_5_contracts_on_44_or_223_or_185_fz',
            field=models.NullBooleanField(verbose_name='Факт исполнения не менее 5 контрактов, заключенных в рамках законов № 44-ФЗ (включая № 94-ФЗ), 223-ФЗ, 185-ФЗ (615 ПП)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_has_garantor_for_advance_related_requirements',
            field=models.NullBooleanField(verbose_name='Наличие Поручителя юридического лица удовлетворяющим одному из предыдущих трех условий'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_last_year_revenue_higher_in_5_times_than_all_bank_bgs',
            field=models.NullBooleanField(verbose_name='Выручка Клиента за последний завершенный год не менее, чем в 5 раз превышает сумму запрашиваемой и действующих в Банке гарантий'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_need_to_check_real_of_issuer_activity',
            field=models.NullBooleanField(verbose_name='Есть необходимость оценки реальности деятельности'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_positive_lawyers_department_conclusion',
            field=models.NullBooleanField(verbose_name='Наличие положительного Заключения ПУ (в соответствии с Приказом по проверке ПУ)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_positive_security_department_conclusion',
            field=models.NullBooleanField(verbose_name='Наличие положительного Заключения СБ'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_real_of_issuer_activity_confirms',
            field=models.NullBooleanField(verbose_name='Реальность деятельности подтверждается'),
        ),
    ]
