# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0097_issue_tender_final_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issuer_oktmo',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='код ОКТМО заявителя'),
        ),
    ]
