# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0099_issue_docs_mgmt_conclusion_manual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_contract_corresponds_issuer_activity',
            field=models.NullBooleanField(verbose_name='Контракт соответствует профилю деятельности клиента'),
        ),
    ]
