# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0101_rebuild_issuebgprodaffiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total_bank_liabilities_vol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='объем обязательств банка'),
        ),
    ]
