# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0102_issue_total_bank_liabilities_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='contract_advance_requirements_fails',
            field=models.NullBooleanField(verbose_name='Не выполняются требования к авансированию (при наличии в контракте аванса)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_has_bad_credit_history',
            field=models.NullBooleanField(verbose_name='Наличие текущей просроченной ссудной задолженности и отрицательной кредитной истории в кредитных организациях'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_issuer_has_blocked_bank_account',
            field=models.NullBooleanField(verbose_name='Наличие информации о блокировке счетов'),
        ),
    ]
