# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0103_add_big_domc_related_issue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='persons_can_acts_as_issuer_and_perms_term_info',
            field=models.TextField(blank=True, default='', verbose_name='Сведения о физических лицах, имеющих право действовать от имени Принципала без доверенности, срок окончания полномочий'),
        ),
    ]
