# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0104_issue_persons_can_acts_as_issuer_and_perms_term_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lawyers_dep_recommendations',
            field=models.TextField(blank=True, default='', help_text='Сотрудником правового управления должны быть оценена актуальность и достаточность предоставленных документов (устав и изменения к нему, документы, подтверждающие полномочия руководителя (включая сроки), соблюдение процедуры одобрения сделок (если подлежат одобрению по специальным основаниям). Обращено внимание на соблюдение процессуальных процедур при оформлении уставных документов.', verbose_name='Сведения о физических лицах, имеющих право действовать от имени Принципала без доверенности, срок окончания полномочий'),
        ),
    ]
