# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0105_issue_lawyers_dep_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='lawyers_dep_conclusion_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers_dep_conclusion_docs_links', to='marer.Document'),
        ),
    ]
