# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0106_issue_lawyers_dep_conclusion_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='balance_code_1300_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='чистые активы за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_1300_offset_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='чистые активы за последний год'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_1600_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='валюта баланса за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_1600_offset_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='валюта баланса за последний год'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_2110_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='выручка за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_2110_offset_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='выручка за последний год'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_2110_offset_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='выручка за предыдущий год'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_2400_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='прибыль за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_code_2400_offset_1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='прибыль за последний год'),
        ),
    ]
