# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0107_set_no_decimals_in_issue_balance_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='last name'),
        ),
    ]
