# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0108_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_contract_corresponds_issuer_activity',
            field=models.IntegerField(blank=True, choices=[(None, 'Неизвестно'), (1, 'Да — 1 балл рейтинга'), (2, 'Да — 2 балла рейтинга'), (4, 'Да — 4 балла рейтинга'), (6, 'Нет — 6 баллов рейтинга')], null=True, verbose_name='Соответствие контракта профилю деятельности клиента'),
        ),
    ]
