# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0109_alter_issue_is_contract_corresponds_issuer_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='is_need_to_check_real_of_issuer_activity',
            field=models.NullBooleanField(default=False, verbose_name='Есть необходимость оценки реальности деятельности'),
        ),
    ]
