# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0110_disable_issue_is_need_to_check_real_of_issuer_activity_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='final_documents_operations_management_conclusion_override',
            field=models.NullBooleanField(verbose_name='Принудительное решение УРДО в спорных ситуациях'),
        ),
    ]
