# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0111_issue_final_documents_operations_management_conclusion_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tender_start_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='начальная цена тендера'),
        ),
    ]
