# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0112_alter_issue_tender_start_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='payment_of_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_of_fee', to='marer.Document'),
        ),
    ]
