# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0113_add_payment_of_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total_credit_pay_term_expiration_events',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество случаев просрочки'),
        ),
    ]
