# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0115_issue_total_credit_pay_term_overdue_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueclarificationmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
