# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0116_set_issueclarificationmessage_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_arbitr_ru_site',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации на сайте Арбитражного суда РФ'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_bank_abs',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации по АБС Банка'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_credit_history',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации по кредитной истории'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_fns_site',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации на сайте ФНС России'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_fssp',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации на сайте ФССП  России'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_guarantors',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации по поручителям'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_kontur_and_spark',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации в информационной системе "Контур-фокус" / "Спарк"'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_persons_have_impact_on_issue_activity',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации по лицам, имеющим влияние на деятельность юридического лица '),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_public_sources_sites',
            field=models.NullBooleanField(verbose_name='Получение информации о юридическом лице из открытых интернет источников'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_ros_fin_monitoring',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации на сайте Росфинмониторинга'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_security_db',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации в информационной базе ДБ Банка'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_issuer_bad_info_on_sudrf_ru',
            field=models.NullBooleanField(verbose_name='Наличие негативной информации на сайтах судов общей юрисдикции (мировых судов)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_absent_info_about_court_cases_on_ifns_or_bankrupts_or_contracts_as_defendant',
            field=models.NullBooleanField(verbose_name='Отсутствие наличия информации о судебных разбирательствах по искам, ответчиком по которым является Принципал: по судебным разбирательствам с ИФНС, по заявлениям о признании Принципала несостоятельным (банкротом), по искам неисполнения государственных контрактов'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_absent_info_about_prev_convictions_on_issuer_head_or_shareholders_or_participants_or_guarantor',
            field=models.NullBooleanField(verbose_name='Отсутствие судимостей в отношении физических лиц (генеральный директор, участники юридического лица (c наибольшей долей участия, Поручитель)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_courts_cases_as_defendant_and_its_acts_info',
            field=models.TextField(blank=True, default='', verbose_name='Информация о судебных разбирательствах Принципала (в качестве ответчика), о находящихся в суде делах и принятых по ним судебным актам'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_fact_address_check',
            field=models.NullBooleanField(help_text='Проверка документов, подтверждающих основание нахождения по адресу, заявленному как фактический, проверка компании арендодателя (как действующего  юридического лица, так и индивидуального предпринимателя) на наличие государственной регистрации в налоговых органах', verbose_name='Проверка адреса, заявленного Принципалом как фактического'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer_shareholders_participants_or_self_court_cases_info',
            field=models.TextField(blank=True, default='', verbose_name='Данные о Принципале, его участниках в базе данных исполнительных производств'),
        ),
        migrations.AddField(
            model_name='issue',
            name='validity_of_shareholders_participants_issuer_head_passports',
            field=models.NullBooleanField(verbose_name='Действительность паспортов акционеров/участников, руководителя Принципала'),
        ),
    ]
