# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0117_add_issue_sec_dep_conclusions_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='underwriting_criteria_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwriting_criteria_doc', to='marer.Document'),
        ),
        migrations.AddField(
            model_name='issue',
            name='underwriting_criteria_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка по критериям андеррайтинга'),
        ),
        migrations.AddField(
            model_name='issue',
            name='balance_code_1230_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True,
                                      verbose_name='размер дебиторской задолженности за последний отчетный период'),
        ),
        migrations.AddField(
            model_name='issue',
            name='balance_code_2110_analog_offset_0',
            field=models.DecimalField(blank=True, decimal_places=0,
                                      help_text='выручка за период, аналогичный последнему отчетному периоду, в предыдущем году (например 3 кв 2017 и 3 кв 2016)',
                                      max_digits=32, null=True, verbose_name='выручка за аналогичный период'),
        ),
        migrations.AddField(
            model_name='issue',
            name='biggest_contract_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_arbitration',
            field=models.BooleanField(default=False,
                                      help_text='наличие арбитражей по нарушениям выполнения условий гос. контрактов'),
        ),
        migrations.AddField(
            model_name='issue',
            name='has_fines_on_zakupki_gov_ru',
            field=models.BooleanField(default=False,
                                      help_text='наличие штрафов по контрактом, отраженных на сайте Госзакупок'),
        ),
        migrations.AddField(
            model_name='issue',
            name='similar_contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='similar_contract_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
