# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0117_add_issue_sec_dep_conclusions_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование агента'),
        ),
    ]
