# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0118_user_legal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tender_placement_type',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='способ определения поставщика в тендере'),
        ),
    ]
