# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0121_add_underwriting_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='approval_and_change_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_and_change_sheet', to='marer.Document'),
        ),
    ]
