# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-28 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0123_make_issue_agent_commission_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='agent_comission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Комиссия агента'),
        ),
    ]
