# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0125_user_is_ordinary_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tender_final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='конечная цена тендера'),
        ),
    ]
