# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0128_add_create_from_filed_for_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueproposedocument',
            name='created_from',
        ),
    ]
