# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0129_delete_created_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='prev_signed_application_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_signed_application_doc_links', to='marer.Document'),
        ),
    ]
