# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0130_add_prev_signed_application_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_unassigned_issues_up_to_15m',
            field=models.BooleanField(default=False, verbose_name='Пользователь видит заявки до 15 млн.'),
        ),
    ]
