# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marer', '0131_user_can_view_unassigned_issues_up_to_15m'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bg_extradition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи банковской гарантии'),
        ),
    ]
